wagtail_webstories_editor/models.py
import json

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.admin_url_finder import AdminURLFinder
from wagtail.admin.panels import FieldPanel, PublishingPanel, InlinePanel
from wagtail.contrib.routable_page.models import RoutablePageMixin, path
from wagtail.contrib.settings.models import BaseSiteSetting
from wagtail.models import (
    DraftStateMixin,
    LockableMixin,
    RevisionMixin,
    WorkflowMixin,
    PreviewableMixin, Page, Orderable
)

from wagtail_webstories_editor import get_webstories_listing_page_model


class WebStoriesSetting(ClusterableModel, BaseSiteSetting):
    google_analytics_id = models.CharField(max_length=255, blank=True, null=True,
                                           verbose_name=_("Google Analytics Measurement ID"))
    using_legacy_analytics = models.BooleanField(default=False)
    video_cache = models.BooleanField(default=False)
    auto_advance = models.BooleanField(default=False)
    default_page_duration = models.IntegerField(default=7, blank=True, null=True)

    panels = [
        FieldPanel("google_analytics_id"),
        FieldPanel("using_legacy_analytics"),
        FieldPanel("video_cache"),
        FieldPanel("auto_advance"),
        FieldPanel("default_page_duration"),
        InlinePanel("publisher_logos", heading=_("Publisher Logos"), label=_("Logo"))
    ]

    @property
    def config(self):
        return {
            "googleAnalyticsId": self.google_analytics_id,
            "usingLegacyAnalytics": self.using_legacy_analytics,
            "videoCache": self.video_cache,
            "autoAdvance": self.auto_advance,
            "defaultPageDuration": self.default_page_duration,
        }


class WebStoriesPublisherLogo(Orderable):
    setting = ParentalKey(WebStoriesSetting, related_name="publisher_logos", on_delete=models.CASCADE)
    logo = models.ForeignKey(
        "wagtailimages.Image",
        null=True,
        blank=False,
        on_delete=models.CASCADE,
        related_name="+",
        verbose_name=_("Logo")
    )
    default = models.BooleanField(default=False)


class WebStory(WorkflowMixin, DraftStateMixin, LockableMixin, RevisionMixin, PreviewableMixin, models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, default="Untitled", verbose_name=_("Title"))
    slug = models.CharField(max_length=255, blank=True, null=True, unique=True)
    config = models.JSONField(blank=True, null=True)
    html = models.TextField(blank=True, null=True)

    _revisions = GenericRelation("wagtailcore.Revision", related_query_name="web_story")
    workflow_states = GenericRelation(
        "wagtailcore.WorkflowState",
        content_type_field="base_content_type",
        object_id_field="object_id",
        related_query_name="web_story",
        for_concrete_model=False,
    )

    class Meta:
        verbose_name = _("Web Story")
        verbose_name_plural = _("Web Stories")
        ordering = ["first_published_at", ]

    panels = [
        FieldPanel("title"),
        FieldPanel("slug"),
        FieldPanel("config"),
        FieldPanel("html"),
        PublishingPanel(),
    ]

    def __str__(self):
        return self.title

    @property
    def poster_image_url(self):
        try:
            featured_media = self.config.get("featuredMedia")
            if featured_media and featured_media.get("url"):
                return featured_media.get("url")

            pages = self.config.get("storyData", {}).get("pages")

            for page in pages:
                elements = page.get("elements")
                for element in elements:
                    if element.get("type") == "image":
                        return element.get("resource").get("src")

        except Exception:
            pass

        return None

    def slug_is_available(self, candidate_slug):
        siblings = WebStory.objects.all()

        if self.pk:
            siblings = siblings.exclude(pk=self.pk)

        return not siblings.filter(slug=candidate_slug).exists()

    def full_clean(self, *args, **kwargs):
        candidate_slug = self.slug
        if candidate_slug:
            suffix = 1
            while not self.slug_is_available(candidate_slug):
                suffix += 1
                candidate_slug = "%s-%d" % (self.slug, suffix)
        self.slug = candidate_slug

        super().full_clean(*args, **kwargs)

    @property
    def json_config(self):
        return json.dumps(self.config)

    @property
    def revisions(self):
        return self._revisions

    def get_preview_template(self, request, preview_mode):
        return f"wagtail_webstories_editor/story_detail.html"

    def get_preview_context(self, request, preview_mode):
        return {"story": self}

    def get_parent_link(self, request=None):
        WebStoyListPage = get_webstories_listing_page_model()
        if WebStoyListPage:
            list_page = WebStoyListPage.objects.live().first()
            return list_page.get_full_url(request)
        return None

    def get_link(self, request=None):
        parent_link = self.get_parent_link(request)
        if parent_link:
            suffix = str(self.pk)
            if self.slug:
                suffix = self.slug
            return parent_link + suffix

        return ""

    def get_permalink_template(self, request=None):
        parent_link = self.get_parent_link(request)

        if parent_link:
            return parent_link + "%pagename%/"

        return ""

    def get_story_dashboard_config(self, request=None):
        finder = AdminURLFinder()
        edit_url = finder.get_edit_url(self)

        story = self.get_latest_revision_as_object()

        if request:
            edit_url = request.build_absolute_uri(edit_url)

        created_at = story.last_published_at or story.created_at

        story_data = {
            "id": story.pk,
            "title": self.title,
            "created": created_at.strftime("%Y-%m-%dT%H:%M:%S"),
            "createdGmt": created_at.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "status": "publish" if self.live else "draft",
            "bottomTargetAction": edit_url,
            "editStoryLink": edit_url,
            "capabilities": {
                "hasEditAction": True,
                "hasDeleteAction": False
            },
        }

        try:
            if story.config and story.config.get("featuredMedia"):
                featuredMedia = story.config.get("featuredMedia")
                if featuredMedia and featuredMedia.get("url"):
                    story_data.update({"featuredMediaUrl": featuredMedia.get("url")})
        except Exception:
            pass

        if self.latest_revision:
            story_data.update({
                "modified": self.latest_revision.created_at.strftime("%Y-%m-%dT%H:%M:%SZ")
            })

        link = self.get_link(request)

        if self.live and link:
            story_data.update({
                "link": link,
                "previewLink": link
            })

        return story_data


class AbstractWebStoryListPage(RoutablePageMixin, Page):
    # we should only have one instance of the listing page
    max_count = 1

    class Meta:
        abstract = True

    @property
    def live_stories(self):
        live_webstories_stories = WebStory.objects.filter(live=True).order_by("-last_published_at")
        return live_webstories_stories

    def get_sitemap_urls(self, request=None):
        list_page_sitemap_urls = super(AbstractWebStoryListPage, self).get_sitemap_urls(request)
        list_page_url = self.get_full_url(request=request)

        for story in self.live_stories:
            sitemap_url = {
                "lastmod": story.last_published_at
            }

            if story.slug:
                sitemap_url.update({
                    "location": list_page_url + story.slug
                })
            else:
                sitemap_url.update({
                    "location": list_page_url + str(story.pk)
                })

            list_page_sitemap_urls.append(sitemap_url)

        return list_page_sitemap_urls

    @path('<str:story_id>/')
    def web_story_page(self, request, story_id):
        """
        View function for web story
        """
        try:
            story_id = int(story_id)
            web_story = get_object_or_404(WebStory, live=True, pk=story_id)
        except ValueError:
            web_story = get_object_or_404(WebStory, live=True, slug=story_id)

        return self.render(
            request,
            context_overrides={
                'story': web_story,
            },
            template="wagtail_webstories_editor/story_detail.html"
        )

wagtail_webstories_editor/templates/wagtail_webstories_editor/create_webstory.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags static %}
{% block titletag %}{% blocktrans trimmed with snippet_type_name=model_opts.verbose_name %}New  {{ snippet_type_name }}
{% endblocktrans %}{% endblock %}
{% block bodyclass %}webstory-editor{% endblock %}
{% block content %}
    {% include 'wagtailadmin/shared/headers/slim_header.html' %}
    <div style="display: flex;flex-direction: column;height: 100%">
        <div id="webstory-editor-container" style="flex: 1;height: 100%"></div>
    </div>

    <form action="{{ action_url }}" method="POST" novalidate{% if form.is_multipart %}
          enctype="multipart/form-data"{% endif %} data-edit-form>
        {% csrf_token %}

        <div style="display: none">
            {{ panel.render_form_content }}
        </div>

        <footer class="footer">
            <nav aria-label="{% trans 'Actions' %}">
                <ul>
                    <li class="actions actions--primary footer__container">
                        <div class="dropdown dropup dropdown-button match-width">
                            {{ action_menu.render_html }}
                        </div>
                    </li>
                </ul>
            </nav>
        </footer>
    </form>


{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ media.css }}

    <style>
        .webstory-editor .content-wrapper .content {
            height: 100%;
            padding: 0 !important;
        }

        .webstory-editor .footer .actions {
            width: 250px !important;
        }

        div[class^='constants__PopupContainer'] {
            z-index: 9999 !important;
        }

        .webstory-editor input {
            background-color: transparent;
        }

        .webstory-editor input[type=search], .webstory-editor input[type=url] {
            height: 100%;
            width: 100%;
            background-color: transparent;
            outline: none;
            cursor: pointer;
            font-family: "Google Sans", sans-serif;
            font-size: 14px;
            font-weight: 400;
            letter-spacing: 0;
            line-height: 20px;
            text-decoration: none;
            color: rgb(228, 229, 230);
            border: 1px solid rgb(57, 61, 63);
            padding: 8px 20px 8px 40px;
            border-radius: 4px;
            box-sizing: border-box;
        }

    </style>


{% endblock %}
{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ media.js }}

    <script src="{% static 'wagtailimages/js/image-chooser-modal.js' %}"></script>
    <script src="{% static 'wagtailimages/js/image-chooser.js' %}"></script>

    <script src="{% static 'wagtaildocs/js/document-chooser-modal.js' %}"></script>
    <script src="{% static 'wagtaildocs/js/document-chooser.js' %}"></script>

    <script src="{% static 'wagtailmedia/js/tabs.js' %}"></script>
    <script src="{% static 'wagtailmedia/js/media-chooser-modal.js' %}"></script>
    <script src="{% static 'wagtailmedia/js/media-chooser.js' %}"></script>

    <script src="{% static 'wagtail_webstories_editor/js/story-editor/editor.js' %}"></script>
    <script src="{% static 'wagtail_webstories_editor/js/common.js' %}"></script>


    <script>
        // Set wagtailConfig.ACTIVE_CONTENT_LOCALE if this is a translated page
        // This value may be used by JS widgets on the form
        {% if locale %}
            window.wagtailConfig = window.wagtailConfig || {};
            window.wagtailConfig.ACTIVE_CONTENT_LOCALE = '{{ locale.language_code|escapejs }}';
        {% endif %}
    </script>
    <script>
        const serviceWorkerScriptUrl = "{% static 'wagtail_webstories_editor/js/story-editor/sw.js' %}";
        const elementId = "webstory-editor-container"
        const apiImagesUrl = "{% url 'wagtailapi:images:listing' %}";
        const apiMediaUrl = "{% url 'wagtailapi:media:listing' %}";

        window.mediaAudioChooserUrl = "{% url 'wagtailmedia:chooser_typed' media_type='audio' %}"
        window.mediaVideoChooserUrl = "{% url 'wagtailmedia:chooser_typed' media_type='video' %}"
        window.imageChooserUrl = "{{ imageChooserUrl }}";
        window.documentChooserUrl = "{{ documentChooserUrl }}";
        window.wagtailImageApiUrl = "{% url 'wagtailapi:images:listing' %}";
        window.wagtailMediaApiUrl = "{% url 'wagtailapi:media:listing' %}";
        window.wagtailDocumentApiUrl = "{% url 'wagtailapi:documents:listing' %}";


        const savedConfig = {{ editorConfig|safe }};


        const getMedia = async ({mediaType, searchTerm}) => {
            let media
            if (mediaType === "video") {
                media = await getVideos(apiMediaUrl)
            } else {
                media = await getImages(apiImagesUrl)
            }


            return {
                data: media.items,
                headers: {
                    totalItems: media.meta.totalItems,
                    totalPages: media.meta.totalPages,
                },
            };
        };
        const onSaveStory = (story) => {
            const storyData = WebStories.getStorySaveData(story)
            const {content, ...rest} = storyData
            const {title: {raw: storyTitle}} = rest

            if (storyTitle) {
                $("#id_title").val(storyTitle)
            } else {
                rest.title.raw = $("#id_title").val()
            }

            $("#id_config").val(JSON.stringify(rest))
            $("#id_html").val(content)

        }

        const editorConfig = {
            ...savedConfig,
            apiCallbacks: {
                saveStoryById: (story) => {
                    onSaveStory(story)
                },
                getMedia: getMedia,
            },
            allowedMimeTypes: {
                image: [
                    'image/webp',
                    'image/png',
                    'image/jpeg',
                    'image/gif',
                    'image/svg+xml',
                ],
                audio: [
                    'audio/mpeg',
                    'audio/aac',
                    'audio/wav',
                    'audio/ogg',
                ],
                video: [
                    'video/mp4', 'video/webm'
                ],
                vector: ['image/svg+xml'],
                caption: ['text/vtt'],
            }
        }


        const options = {
            serviceWorkerScriptUrl,
            storyId: null,
        }

        // empty story
        const initialEdits = {story: {}}

        $(document).ready(() => {
            // initialize editor
            WebStories.initializeStoryEditor(elementId, editorConfig, initialEdits, options)
        })


    </script>
{% endblock %}

wagtail_webstories_editor/templates/wagtail_webstories_editor/edit_side_panels.html
{% load wagtailadmin_tags i18n %}

<aside class="form-side form-side--initial" aria-label="{% trans 'Side panels' %}" data-form-side{% if in_explorer %}
       data-form-side-explorer{% endif %}>
    <button type="button" class="form-side__close-button" data-form-side-close-button
            aria-label="{% trans 'Toggle side panel' %}">
        {% icon name="expand-right" %}
    </button>

    <div class="form-side__resize-grip-container">
        <label class="form-side__resize-grip" data-form-side-resize-grip>
            {% comment %}
                By default, the `dir` attribute is inherited from the ancestor
                (i.e. the root `html` element in our case).
                On Chrome and Firefox, moving the slider with left-right arrow keys
                is correctly reversed when dir="rtl". On Safari, this isn't the case.
                So, we explicitly set the `dir` attribute to "ltr" on the input and handle the correct
                direction in the JS code based on the `dir` attribute of the root `html`.
            {% endcomment %}
            <input type="range" step="10" dir="ltr" class="form-side__width-input" name="wagtail-side-panel-width"
                   data-form-side-width-input/>
            <span class="w-sr-only">{% trans 'Side panel width' %}</span>
            <div class="form-side__resize-grip-icon"></div>
        </label>
    </div>

    {% for panel in side_panels %}
        <div class="form-side__panel" data-side-panel="{{ panel.name }}" hidden>
            <h2 id="side-panel-{{ panel.name }}-title" class="w-sr-only">{{ panel.title }}</h2>
            {% component panel %}
        </div>
    {% endfor %}
</aside>

wagtail_webstories_editor/templates/wagtail_webstories_editor/edit_webstory.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailadmin_tags i18n static %}
{% block titletag %}{% blocktrans trimmed with snippet_type_name=model_opts.verbose_name %}Editing
    {{ snippet_type_name }} - {{ object }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}webstory-editor {% if locked_for_user %}content-locked{% endif %}{% endblock %}
{% block content %}
    {% include 'wagtailadmin/shared/headers/slim_header.html' %}
    <div style="display: flex;flex-direction: column;height: 100%">
        <div id="webstory-editor-container" style="flex: 1;height: 100%"></div>
    </div>
    <form id="webstory-form" action="{{ action_url }}" method="POST" novalidate{% if form.is_multipart %}
          enctype="multipart/form-data"{% endif %} data-edit-form>
        {% csrf_token %}
        <div style="display: none">
            {{ panel.render_form_content }}
        </div>
        <footer class="footer">
            <nav aria-label="{% trans 'Actions' %}">
                <ul>
                    <li class="actions actions--primary footer__container">
                        <div class="dropdown dropup dropdown-button match-width {% if view.view_name == 'revisions_revert' %}warning{% endif %}">
                            {{ action_menu.render_html }}
                        </div>
                    </li>
                </ul>
            </nav>
        </footer>
    </form>

{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ media.css }}

    <style>
        .webstory-editor .content-wrapper .content {
            height: 100%;
            padding: 0 !important;
        }

        .webstory-editor .footer .actions {
            width: 250px !important;
        }

        div[class^='constants__PopupContainer'] {
            z-index: 9999 !important;
        }


        .webstory-editor input {
            background-color: transparent;
        }

        .webstory-editor input[type=search], .webstory-editor input[type=url] {
            height: 100%;
            width: 100%;
            background-color: transparent;
            outline: none;
            cursor: pointer;
            font-family: "Google Sans", sans-serif;
            font-size: 14px;
            font-weight: 400;
            letter-spacing: 0;
            line-height: 20px;
            text-decoration: none;
            color: rgb(228, 229, 230);
            border: 1px solid rgb(57, 61, 63);
            padding: 8px 20px 8px 40px;
            border-radius: 4px;
            box-sizing: border-box;
        }


    </style>


{% endblock %}
{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ media.js }}

    <script src="{% static 'wagtailimages/js/image-chooser-modal.js' %}"></script>
    <script src="{% static 'wagtailimages/js/image-chooser.js' %}"></script>

    <script src="{% static 'wagtaildocs/js/document-chooser-modal.js' %}"></script>
    <script src="{% static 'wagtaildocs/js/document-chooser.js' %}"></script>

    <script src="{% static 'wagtailmedia/js/tabs.js' %}"></script>
    <script src="{% static 'wagtailmedia/js/media-chooser-modal.js' %}"></script>
    <script src="{% static 'wagtailmedia/js/media-chooser.js' %}"></script>


    <script src="{% static 'wagtail_webstories_editor/js/story-editor/editor.js' %}"></script>
    <script src="{% static 'wagtail_webstories_editor/js/common.js' %}"></script>

    <script>
        // Set wagtailConfig.ACTIVE_CONTENT_LOCALE if this is a translated page
        // This value may be used by JS widgets on the form
        {% if locale %}
            window.wagtailConfig = window.wagtailConfig || {};
            window.wagtailConfig.ACTIVE_CONTENT_LOCALE = '{{ locale.language_code|escapejs }}';
        {% endif %}
    </script>

    <script>

        const serviceWorkerScriptUrl = "{% static 'wagtail_webstories_editor/js/story-editor/sw.js' %}";
        const elementId = "webstory-editor-container"
        const apiImagesUrl = "{% url 'wagtailapi:images:listing' %}";
        const apiMediaUrl = "{% url 'wagtailapi:media:listing' %}";

        window.mediaAudioChooserUrl = "{% url 'wagtailmedia:chooser_typed' media_type='audio' %}"
        window.mediaVideoChooserUrl = "{% url 'wagtailmedia:chooser_typed' media_type='video' %}"
        window.wagtailImageApiUrl = "{% url 'wagtailapi:images:listing' %}";
        window.wagtailMediaApiUrl = "{% url 'wagtailapi:media:listing' %}";
        window.wagtailDocumentApiUrl = "{% url 'wagtailapi:documents:listing' %}";

        window.imageChooserUrl = "{{ imageChooserUrl }}";
        window.documentChooserUrl = "{{ documentChooserUrl }}";

        const publisherLogosUrl = "{% url 'web_stories_publisher_logos' %}";

        const storyConfig = {{ object.json_config|safe }};
        const storyHtml = "{{ object.html|escapejs }}";
        const permalinkTemplate = "{{ permalink_template }}"
        const storyLink = "{{ story_link }}";
        const isLive = {{ object.live|yesno:"true,false" }};
        const slug = "{{ object.slug|default_if_none:""}}";


        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const storyId = "{{ object.pk }}";


        storyConfig.storyId = storyId

        const story = {
            ...storyConfig,
            content: storyHtml,
        }

        if (slug) {
            story.slug = slug
        }

        if (storyLink && isLive) {
            story.link = storyLink
        }

        if (permalinkTemplate) {
            story.permalinkTemplate = permalinkTemplate
        }


        const options = {
            serviceWorkerScriptUrl,
            initialEdits: {story},
            storyId: "{{ object.pk }}",
        }

        const getMedia = async ({mediaType, searchTerm}) => {
            let media
            if (mediaType === "video") {
                media = await getVideos(apiMediaUrl)
            } else {
                media = await getImages(apiImagesUrl)
            }

            return {
                data: media.items,
                headers: {
                    totalItems: media.meta.totalItems,
                    totalPages: media.meta.totalPages,
                },
            };
        };

        const onSaveStory = (story) => {
            const storyData = WebStories.getStorySaveData(story)
            const {content, ...rest} = storyData
            const {title: {raw: storyTitle}, slug} = rest

            if (storyTitle) {
                $("#id_title").val(storyTitle)
            } else {
                rest.title.raw = $("#id_title").val()
            }

            if (slug && slug !== storyId) {
                $("#id_slug").val(slug)
            }

            $("#id_config").val(JSON.stringify(rest))
            $("#id_html").val(content)

        }

        const editorConfig = {
            apiCallbacks: {
                saveStoryById: (story) => {
                    onSaveStory(story)
                },
                getMedia: getMedia,
                getPublisherLogos: (logosPath) => {
                    return fetch(logosPath).then((res => res.json()))
                },
                addPublisherLogo: (logosPath, logoId) => {
                    const payload = {
                        id: logoId
                    }

                    let props = {
                        method: "POST",
                        body: JSON.stringify(payload),
                        headers: {
                            "X-CSRFToken": getCookie("csrftoken"),
                            "Content-Type": "application/json;charset=UTF-8"
                        },
                        mode: "same-origin",
                    }
                    return fetch(logosPath, props).then(res => res.json())
                }
            },
            api: {
                publisherLogos: publisherLogosUrl
            },
            allowedMimeTypes: {
                image: [
                    'image/webp',
                    'image/png',
                    'image/jpeg',
                    'image/gif',
                    'image/svg+xml',
                ],
                audio: [
                    'audio/mpeg',
                    'audio/aac',
                    'audio/wav',
                    'audio/ogg',
                ],
                video: [
                    'video/mp4', 'video/webm'
                ],
                vector: ['image/svg+xml'],
                caption: ['text/vtt'],
            }
        }

        const initialEdits = {story}

        $(document).ready(() => {
            // initialize editor
            WebStories.initializeStoryEditor(elementId, editorConfig, initialEdits, options)
        })

    </script>
    {% if workflow_enabled %}
        {% include "wagtailadmin/shared/_workflow_init.html" %}
    {% endif %}
{% endblock %}

wagtail_webstories_editor/templates/wagtail_webstories_editor/story_detail.html
{{ story.html|safe }}